# config/serial_params.yaml
serial_node:
  ros__parameters:
    serial_name: "/dev/ttyACM1"
    baud_rate: 115200
    max_try: 100
    patrol1:
      x: -3.29
      y: 2.11
      yaw: 0.0
    patrol2:
      x: 1.28
      y: 1.16
      yaw: 0.0
    home:
      x: -0.019
      y: -0.138
      yaw: 0.0
    is_decision: true
    socket_send_name: "/tmp/serial_mux.sock"
    socket_receive_name: "/tmp/serial_nav.sock"
    sending_method: "socket"  # 可选值: "serial" 或 "socket"
