# config/serial_params.yaml
serial_node:
  ros__parameters:
    serial_name: "/dev/ttyACM1"
    baud_rate: 115200
    max_try: 100
    patrol1:
      x: 2.54
      y: -5.89
      yaw: 0.0
      wait_time: 7.0
    patrol2:
      x: 6.15
      y: -2.98
      yaw: 0.0
      wait_time: 9.0
    patrol3:
      x: 8.75
      y: -2.73
      yaw: 0.0
      wait_time: 14.0
    patrol4:
      x: 2.18
      y: -7.78
      yaw: 0.0
      wait_time: 7.0
    HitOutpost:
      x: 8.75
      y: -2.73
      yaw: 0.0
      wait_time: 5.0
    home:
      x: -3.47
      y: -3.9
      yaw: 0.0
      wait_time: 5.0
    go_home_hp: 85
    go_home_projectile_allowance: 15
    become_home_hp: 350
    become_home_projectile_allowance: 100
    is_decision: true
    socket_send_name: "/tmp/serial_mux.sock"
    socket_receive_name: "/tmp/serial_nav.sock"
    sending_method: "socket"  # 可选值: "serial" 或 "socket"